version: "3.8"
# Docker Compose version 2.x.x

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - network

networks:
  network:
    driver: bridge
